version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
      time: "12:00"
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: "/spl-manager"
    schedule:
      interval: monthly
      time: "12:00"
    open-pull-requests-limit: 10
