# PRE COMMIT CONFIGURATION FILE
# ---------------------------------------------------------
# Copyright (C) 2021 Nextpart Security Intelligence GmbH
# All rights reserved. - Proprietary and confidential

# The pre-commit file serves only to detect formatting errors or
# similar and is not intended to change the code by e.g. sorting
# imports, because that is what the lint in tox is for.

repos:
  # Common stuff and checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast # Simply check whether the files parse as valid python.
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-docstring-first # Checks a common error of defining a docstring after code.
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls.
      - id: fix-encoding-pragma # Add "# -*- coding: utf-8 -*-"" to the top of python files
      - id: trailing-whitespace # This hook trims trailing whitespace.
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline.

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        exclude: &fixtures tests/functional/|tests/input|tests/extensions/data|tests/regrtest_data/|tests/data/
        args:
          - --in-place
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --ignore-init-module-imports

  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: isort (python)
        args: [--settings-file, pyproject.toml]
      - id: isort
        name: isort (cython)
        types: [cython]
        args: [--settings-file, pyproject.toml]
      - id: isort
        name: isort (pyi)
        types: [pyi]
        args: [--settings-file, pyproject.toml]

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=100"]

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==21.7b0]
        exclude: ^.github/

  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        files: ".ipynb"
        args: ["--keep-output", "--extra-keys", "metadata.kernelspec"]

  - repo: https://github.com/myint/rstcheck
    rev: master # "3f92957478422df87bd730abde66f089cc1ee19b"
    hooks:
      - id: rstcheck
        args:
          [
            "--report=warning",
            "--ignore-directives=panels,tabbed,mdinclude,dropdown,link-button,needtable,doctest,needflow,req,spec,impl,test,test-report",
          ]
        types: [text] # necessary to include ChangeLog file
        files: ^(ChangeLog|doc/(.*/)*.*\.rst)

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.2
    hooks:
      - id: python-safety-dependencies-check
        args: [
            # Ignore 41002:
            # > coverage, installed 5.5, affected <6.0b1, id 41002:
            # > Coverage 6.0b1 starts to use a modern hash algorithm (sha256)
            # > when fingerprinting for high-security environments.
            # Coverage is a transitive, dev-only dependency of pytest-cov that
            # cannot easily be updated on its own, especially without adding it
            # as a direct dependency of the project.
            "--ignore=41002",
          ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
      - id: pyupgrade
