default:
  connections:
    localhost:
      host: "localhost"
      port: 8090
  # logging:
  #   version: 1
  #   formatters:
  #     simple:
  #       format: '%(asctime)s %(levelname)s | %(funcName)s:%(lineno)d - %(message)s'
  #   handlers:
  #     console:
  #       class: logging.StreamHandler
  #       level: INFO
  #       formatter: simple
  #       stream: ext://sys.stdout
  #   loggers:
  #     simpleExample:
  #       level: INFO
  #       handlers: [console]
  #       propagate: no
  #   root:
  #     level: INFO
  #     handlers: [console]

  samples:
    WinHostMon:
      src: rb-onprem
      query: |
        index="*"
      earliest: -7d@d
      latest: now
    Aruba:
      src: rb-onprem
      query: |
        index="*"
      earliest: -7d@d
      latest: now
    GuardiaOS:
      src: nxtp-onprem
      query: |
        index="guardia-os" environment="development"
        | reverse
        | table index, host, source, sourcetype, _raw, _time
      earliest: -1d@d
      latest: now
    GuardiaApp:
      src: nxtp-onprem
      query: |
        index="guardia-app" environment="development"
        | reverse
        | table index, host, source, sourcetype, _raw, _time
      earliest: -7d@d
      latest: now
  splunkbase:
    auth_uri: https://api.splunk.com/2.0/rest/login/splunk
    appinspect_uri: https://appinspect.splunk.com/v1/app
    apps:
      addon_builder:
        id: "2962"
        version: 4.0.0
      # azure_app:
      #   id: "4882"
      #   version: 1.1.0
      azure_ta:
        id: "3757"
        version: 3.2.0
      cim:
        id: "1621"
        version: 4.20.2
      dashboards_app:
        id: "4710"
        version: 0.9.0
      # essential:
      #   id: "5512"
      #   version: 1.0.0
      eventgen:
        id: "1924"
        version: 7.2.1
      # horizon_viz:
      #   id: "3117"
      #   version: 1.5.0
      # infra_ta:
      #   id: "4217"
      #   version: 2.2.4
      # it_essential:
      #   id: "5390"
      #   version: 1.1.2
      # knowledge_objects_app:
      #   id: "5399"
      #   version: 1.0.26
      lookup_edit:
        id: "1724"
        version: 3.5.0
      # monitor_alert_pack:
      #   id: "4808"
      #   version: 2.0.3
      # ms_cloud_ta:
      #   id: "3110"
      #   version: 4.2.0
      ms_graph_ta:
        id: "4564"
        version: 1.2.3
      # nix_ta:
      #   id: "833"
      #   version: 8.3.1
      o365_app:
        id: "3786"
        version: 3.2.2
      o365_ta:
        id: "4055"
        version: 2.2.0
      # sankey_viz:
      #   id: "3112"
      #   version: 1.6.0
      # sec_essential:
      #   id: "3435"
      #   version: 3.4.0
      servicenow_ta:
        id: "1928"
        version: 7.1.1
      # stream_forwarders:
      #   id: "5238"
      #   version: 8.0.1
      timeline_viz:
        id: "3120"
        version: 1.6.1
  docker:
    socket: unix://var/run/docker.sock
    image: splunk/splunk:8.2.4
    package_image: nextpartdev.azurecr.io/splunk/package:dev
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
      SPLUNK_PASSWORD: mySplunkDevPw
      SPLUNK_CMD_1: "restart"
      PATH: $PATH:/opt/splunk/bin
      SPLUNK_CMD:
        "add licenses -auth admin:${SPLUNK_PASSWORD} /hack/splunk/licenses/*.lic || true"
  apps:
    exclude:
      - 075-cloudworks
      - 100-cloudworks-wlm
      - 100-whisper
      - 100-whisper-common
      - 100-whisper-searchhead
      - alert_logevent
      - alert_logevent
      - alert_webhook
      - alert_webhook
      - appsbrowser
      - cloud_administration
      - dmc
      - framework
      - introspection_generator_addon
      - journald_input
      - launcher
      - learned
      - legacy
      - lookup_editor
      - prometheus
      - python_upgrade_readiness_app
      - sample_app
      - splunk_app_addon-builder
      - splunk_archiver
      - splunk_enterprise_on_docker
      - splunk_gdi
      - splunk_httpinput
      - splunk_instrumentation
      - splunk_internal_metrics
      - splunk_metrics_workspace
      - splunk_monitoring_console
      - splunk_rapid_diag
      - splunk_secure_gateway
      - splunkclouduf
      - SplunkForwarder
      - SplunkLightForwarder
      - tos
      - user-prefs
