default:
  connections:
    # local Docker instance:
    localhost:
      host: "localhost"
      port: 8090
      username: "admin"
      password: "mySplunkDevPw"
  docker:
    package_image: myregistry.azurecr.io/splunk/package:dev
  splunkbase:
    username: ""
    password: ""
