default:
  connections:
    # local Docker instance:
    localhost:
      host: "localhost"
      port: 8090
      username: "admin"
      password: "mySplunkDevPw"
  docker:
    package_image: nextpart/splunk-package:latest
    environment:
      SPLUNK_PASSWORD: mySplunkDevPw
  splunkbase:
    username: ""
    password: ""
